openapi: 3.0.3
info:
  title: Bleve Search Query
  version: "1.0.0"
  description: An OpenAPI specification for Bleve search query objects.
paths: {}
components:
  schemas:
    Boost:
      type: number
      format: double
      description: A floating-point number used to decrease or increase the relevance scores of a query.
      default: 1.0
      nullable: true
    Fuzziness:
      description: The fuzziness of the query. Can be an integer or "auto".
      anyOf:
        - type: integer
          format: int32
        - type: string
          enum:
            - auto
    GeoPoint:
      type: object
      properties:
        lon:
          type: number
          format: double
        lat:
          type: number
          format: double
    TermQuery:
      type: object
      properties:
        term:
          type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - term
    MatchQuery:
      type: object
      properties:
        match:
          type: string
        field:
          type: string
        analyzer:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
        prefix_length:
          type: integer
          format: int32
        fuzziness:
          $ref: "#/components/schemas/Fuzziness"
        operator:
          type: string
          enum:
            - or
            - and
      required:
        - match
    MatchPhraseQuery:
      type: object
      properties:
        match_phrase:
          type: string
        field:
          type: string
        analyzer:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
        fuzziness:
          $ref: "#/components/schemas/Fuzziness"
      required:
        - match_phrase
    PhraseQuery:
      type: object
      properties:
        terms:
          type: array
          items:
            type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
        fuzziness:
          $ref: "#/components/schemas/Fuzziness"
      required:
        - terms
    MultiPhraseQuery:
      type: object
      properties:
        terms:
          type: array
          items:
            type: array
            items:
              type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
        fuzziness:
          $ref: "#/components/schemas/Fuzziness"
      required:
        - terms
    FuzzyQuery:
      type: object
      properties:
        term:
          type: string
        prefix_length:
          type: integer
          format: int32
        fuzziness:
          $ref: "#/components/schemas/Fuzziness"
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - term
    PrefixQuery:
      type: object
      properties:
        prefix:
          type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - prefix
    RegexpQuery:
      type: object
      properties:
        regexp:
          type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - regexp
    WildcardQuery:
      type: object
      properties:
        wildcard:
          type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - wildcard
    QueryStringQuery:
      type: object
      properties:
        query:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - query
    NumericRangeQuery:
      type: object
      properties:
        min:
          type: number
          format: double
          nullable: true
        max:
          type: number
          format: double
          nullable: true
        inclusive_min:
          type: boolean
          nullable: true
        inclusive_max:
          type: boolean
          nullable: true
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
    TermRangeQuery:
      type: object
      properties:
        min:
          type: string
          nullable: true
        max:
          type: string
          nullable: true
        inclusive_min:
          type: boolean
          nullable: true
        inclusive_max:
          type: boolean
          nullable: true
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
    DateRangeStringQuery:
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        inclusive_start:
          type: boolean
          nullable: true
        inclusive_end:
          type: boolean
          nullable: true
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
        datetime_parser:
          type: string
    BooleanQuery:
      type: object
      properties:
        must:
          $ref: "#/components/schemas/ConjunctionQuery"
        should:
          $ref: "#/components/schemas/DisjunctionQuery"
        must_not:
          $ref: "#/components/schemas/DisjunctionQuery"
        filter:
          $ref: "#/components/schemas/Query"
        boost:
          $ref: "#/components/schemas/Boost"
    ConjunctionQuery:
      type: object
      properties:
        conjuncts:
          type: array
          items:
            $ref: "#/components/schemas/Query"
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - conjuncts
    DisjunctionQuery:
      type: object
      properties:
        disjuncts:
          type: array
          items:
            $ref: "#/components/schemas/Query"
        boost:
          $ref: "#/components/schemas/Boost"
        min:
          type: number
          format: double
      required:
        - disjuncts
    MatchAllQuery:
      type: object
      properties:
        match_all:
          type: object
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - match_all
    MatchNoneQuery:
      type: object
      properties:
        match_none:
          type: object
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - match_none
    DocIdQuery:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - ids
    BoolFieldQuery:
      type: object
      properties:
        bool:
          type: boolean
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - bool
    IPRangeQuery:
      type: object
      properties:
        cidr:
          type: string
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - cidr
    GeoBoundingBoxQuery:
      type: object
      properties:
        top_left:
          type: array
          items:
            type: number
            format: double
          minItems: 2
          maxItems: 2
          description: "[lon, lat]"
        bottom_right:
          type: array
          items:
            type: number
            format: double
          minItems: 2
          maxItems: 2
          description: "[lon, lat]"
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - top_left
        - bottom_right
    GeoDistanceQuery:
      type: object
      properties:
        location:
          type: array
          items:
            type: number
            format: double
          minItems: 2
          maxItems: 2
          description: "[lon, lat]"
        distance:
          type: string
          example: "10km"
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - location
        - distance
    GeoBoundingPolygonQuery:
      type: object
      properties:
        polygon_points:
          type: array
          items:
            $ref: "#/components/schemas/GeoPoint"
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - polygon_points
    GeoShape:
      type: object
      description: A GeoJSON shape object. This is a simplified representation.
      properties:
        type:
          type: string
        coordinates:
          type: array
      required:
        - type
        - coordinates
    GeoShapeGeometry:
      type: object
      properties:
        shape:
          $ref: "#/components/schemas/GeoShape"
        relation:
          type: string
          enum:
            - intersects
            - contains
            - within
      required:
        - shape
        - relation
    GeoShapeQuery:
      type: object
      properties:
        geometry:
          $ref: "#/components/schemas/GeoShapeGeometry"
        field:
          type: string
        boost:
          $ref: "#/components/schemas/Boost"
      required:
        - geometry
    #KNNQuery:
    #  type: object
    #  properties:
    #    field:
    #      type: string
    #    vector:
    #      type: array
    #      items:
    #        type: number
    #        format: float
    #    k:
    #      type: integer
    #      format: int64
    #    boost:
    #      $ref: "#/components/schemas/Boost"
    #    params:
    #      type: object
    #  required:
    #    - field
    #    - vector
    #    - k
    Query:
      oneOf:
        - $ref: "#/components/schemas/TermQuery"
        - $ref: "#/components/schemas/MatchQuery"
        - $ref: "#/components/schemas/MatchPhraseQuery"
        - $ref: "#/components/schemas/PhraseQuery"
        - $ref: "#/components/schemas/MultiPhraseQuery"
        - $ref: "#/components/schemas/FuzzyQuery"
        - $ref: "#/components/schemas/PrefixQuery"
        - $ref: "#/components/schemas/RegexpQuery"
        - $ref: "#/components/schemas/WildcardQuery"
        - $ref: "#/components/schemas/QueryStringQuery"
        - $ref: "#/components/schemas/NumericRangeQuery"
        - $ref: "#/components/schemas/TermRangeQuery"
        - $ref: "#/components/schemas/DateRangeStringQuery"
        - $ref: "#/components/schemas/BooleanQuery"
        - $ref: "#/components/schemas/ConjunctionQuery"
        - $ref: "#/components/schemas/DisjunctionQuery"
        - $ref: "#/components/schemas/MatchAllQuery"
        - $ref: "#/components/schemas/MatchNoneQuery"
        - $ref: "#/components/schemas/DocIdQuery"
        - $ref: "#/components/schemas/BoolFieldQuery"
        - $ref: "#/components/schemas/IPRangeQuery"
        - $ref: "#/components/schemas/GeoBoundingBoxQuery"
        - $ref: "#/components/schemas/GeoDistanceQuery"
        - $ref: "#/components/schemas/GeoBoundingPolygonQuery"
        - $ref: "#/components/schemas/GeoShapeQuery"
        #- $ref: "#/components/schemas/KNNQuery"
