import createClient from "openapi-fetch";
import type { paths } from "./antfly-api"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:8080/" });

const {
  data, // only present if 2XX response
  error, // only present if 4XX or 5XX response
} = client.POST("/query", {
  params: {
    path: { post_id: "123" },
  },
});

await client.GET("/table", {
  body: {
    title: "My New Post",
  },
});
